name: Prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [development]
jobs:
  eslint:
    name: Run prettier scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prettier
        run: npm run format
        continue-on-error: true

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email "yo@facund-cachan.dev"
          git config --global user.name "Facundo Cachan"
          git commit -am "Automated changes- Prettier"
          git push
